config/routes.rb
Rails.application.routes.draw do
  get 'index' => 'home#index'
  root 'home#index'
  resource :users
  resource :sessions, only: [:new, :create, :destroy]
  delete 'log_out' => 'sessions#destroy'

  resources :conversations do
    resources :messages
  end
  get 'conversations/display' => 'conversations#display'
  get 'conversations/load_more' => 'conversations#load_more'

  resources :friendships, only: [:create]
  get 'users/block' => 'users#block'
  get 'users/un_block' => 'users#un_block'
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  # before_create :set_type, :create_unread_messages

  scope :involving, -> (user) do
    where('conversations.sender_id =? OR conversations.recipient_id =?', user.id, user.id)
  end

  scope :between, -> (sender_id, recipient_id) do
    where('(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)', sender_id, recipient_id, recipient_id, sender_id)
  end

  def self.order_by_messages
    c_ids = Message.order(created_at: :DESC).pluck(:conversation_id).uniq
    where(id: c_ids)
  end

  def last_message
    messages.last
  end

  def unread_messages(recipient)
    messages.where.not(user: recipient).where(unread: true)
  end

  def count_unread_messages(recipient)
    unread_messages(recipient).count
  end

  def self.conversation_of(user_id, friend_id)
    Conversation.between(user_id, friend_id).first
  end

  def members
    u_ids = Message.where(conversation: self).pluck(:user_id)
    User.where(id: [u_ids])
  end

  def recipients(sender)
    # for chat room
    # members.reject { |member| member.id == sender.id }
    members.reject { |member| member.id == sender.id }.first
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  layout false
  before_action :read_messages, only: [:show, :display]

  def index
    redirect_to root_path
  end

  def show
    @conversation = Conversation.includes(:messages).find(params[:id])
    @messages = load_more_message
    respond_to :js
  end

  def create
    @conversation = Conversation.between(params[:sender_id],
                                         params[:recipient_id]).first
    @conversation ||= Conversation.create!(conversation_params)
    respond_to :js
  end

  def display
    @recipient = User.find(params[:recipient_id])
    @conversation = current_user.find_conversation_by(@recipient)
    @conversation ||= Conversation.create(sender: @current_user,
                                          recipient: @recipient)
    @messages = load_more_message
    respond_to :js
  end

  def load_more
    @conversation ||= Conversation.includes(:messages).find(params[:id])
    @messages = load_more_message
    respond_to :js
  end

  def destroy
    @conversation = Conversation.find(params[:id])
    Message.where(conversation: @conversation, user: current_user).destroy_all
    respond_to :js
  end

  private

  def load_more_message
    page = params[:page] || 1
    @conversation.messages.paginate(page: page).order(created_at: :desc).reverse
  end

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  def interlocutor(conversation)
    current_user == conversation.recipient ? conversation.sender : conversation.recipient
  end

  def read_messages
    @conversation.messages.update_all(unread: false)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_messages.html.erb
<%if conversation.messages.present? %>
    <%if conversation.messages.count <= page %>
        <div class="text-center loadmore">
            <%= link_to 'Load More Messages', conversations_load_more_path(conversation_id: conversation.id, page: page), remote: true, class: 'btn btn-default'%>
        </div>
    <% end %>
    <% conversation.messages.last(page).each do |message| %>
        <div class="message-feed <%= media_or_right(message) %>">
            <div class="pull-<%= left_or_right(message) %>">
                <img src="<%= message.user.avatar_url || 'https://bootdey.com/img/Content/avatar/avatar1.png' %>" alt="" class="img-avatar">
            </div>
            <div class="media-body">
                <div class="mf-content">
                    <%= message.body %>
                </div>
                <small class="mf-date"><i class="fa fa-clock-o"></i><%= chat_format_time(message.created_at) %></small>
            </div>
        </div>
    <% end %>
<% else %>
    <div class="message-feed media">
        <div class="pull-left">
            <img src="<%= current_user.avatar_url || 'https://bootdey.com/img/Content/avatar/avatar1.png' %>"  alt="" class="img-avatar">
        </div>
        <div class="media-body">
            <div class="mf-content">
                hi ! welcome to Cucumbercat 
            </div>
            <small class="mf-date"><i class="fa fa-clock-o"></i> <%= chat_format_time(Time.now) %></small>
        </div>
    </div>
<% end %>

app/views/conversations/display.js.erb
$("#messages-body").html('<%= escape_javascript(render "conversations/messages", conversation: @conversation, page: @page ) %>');
$('#messages-form').html('<%= escape_javascript(render "messages/form", conversation: @conversation) %>');
$('#topbar').html('<%= escape_javascript(render "home/topbar", conversation: @conversation, friend: @friend) %>');

app/views/conversations/load_more.js.erb
$("#messages-body").html('<%= escape_javascript(render "conversations/messages", conversation: @conversation, page: @page ) %>');