config/routes.rb
Rails.application.routes.draw do
  get 'index' => 'home#index'
  root 'home#index'
  resource :users
  resource :sessions, only: [:new, :create, :destroy]
  delete 'log_out' => 'sessions#destroy'

  resources :conversations do
    resources :messages
  end
  get 'conversations/display' => 'conversations#display'
  get 'conversations/load_more' => 'conversations#load_more'

  resources :friendships, only: [:create]
  get 'users/block' => 'users#block'
  get 'users/un_block' => 'users#un_block'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, :email, :gender, presence: true
  validates :name, length: { minimum: 2, message: 'name is too short' }
  validates :name, length: { maximum: 120, message: 'name is too long' }
  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/, message: 'only allows letters', on: :create }

  has_many :conversations, foreign_key: :sender_id
  has_many :friendships, -> { where(blocked: false) }
  has_many :friends, through: :friendships, class_name: 'User'

  after_create :create_default_conversation

  def blockers
    block_ids = Friendship.where(friend: self, blocked: true).pluck(:friend_id)
    User.where(id: block_ids)
  end

  def blocked_by(user)
    # user blocked self
    Friendship.find_by(user: self, friend: user).blocked == true
  end

  def find_conversation_by(user)
    Conversation.between(self.id, user.id).first
  end

  private

  def create_default_conversation
    Conversation.create(sender_id: self.id, recipient_id: self.id) unless self.id == 1
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "hi #{@user.name}"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:error] = @user.errors.messages.to_s
      render 'new'
    end
  end

  def block
    friend = User.find(params[:friend_id])
    User.transaction do
      # for querry in models we using inverse
      Friendship.find_by(user: friend, friend: current_user).update(blocked: true)
    end
  end

  def un_block
    friend = User.find(params[:friend_id])
    User.transaction do
      Friendship.find_by(user: friend, friend: current_user).update(blocked: false)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :gender)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end
end

app/views/users/_forgot_password.html.erb
<!-- FORGOT PASSWORD FORM -->
<div class="text-center" style="padding:50px 0">
  <div class="logo">forgot password</div>
  <!-- Main Form -->
  <div class="login-form-1">
    <form id="forgot-password-form" class="text-left">
      <div class="etc-login-form">
        <p>When you fill in your registered email address, you will be sent instructions on how to reset your password.</p>
      </div>
      <div class="login-form-main-message"></div>
      <div class="main-login-form">
        <div class="login-group">
          <div class="form-group">
            <label for="fp_email" class="sr-only">Email address</label>
            <input type="text" class="form-control" id="fp_email" name="fp_email" placeholder="email address">
          </div>
        </div>
        <button type="submit" class="login-button"><i class="fa fa-chevron-right"></i></button>
      </div>
      <% if params[:show_hint] %>
        <div class="etc-login-form">
          <p>already have an account? <a href="#">login here</a></p>
          <p><%= link_to("new user?", new_users_path) %></p>
        </div>
      <% end %>
    </form>
  </div>
  <!-- end:Main Form -->

app/views/users/_register.html.erb
<!-- REGISTRATION FORM -->
<div class="text-center" style="padding:50px 0">
  <div class="logo">register</div>
  <!-- Main Form -->
  <div class="login-form-1">
    <%= form_for @user, id: "register-form", class: "text-left" do |f| %>
      <div class="login-form-main-message"></div>
      <div class="main-login-form">
        <div class="login-group">
          <div class="form-group">
            <%= f.label :name, for: 'reg_username', class: "sr-only"%>
            <%= f.text_field :name, for: 'reg_username',id: "reg_username", class: "form-control", placeholder: "username"%>
          </div>
          <div class="form-group">
            <%= f.label :password, for: 'reg_password', class: "sr-only"%>
            <div class="password">
              <%= f.password_field :password, for: 'reg_password',id: "reg_password", class: "form-control", placeholder: "password"%>
              <span class="glyphicon glyphicon-eye-open"></span>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :email, for: 'reg_email', class: "sr-only"%>
            <%= f.text_field :email, for: 'reg_email',id: "reg_email", class: "form-control", placeholder: "email"%>
          </div>
          
          <div class="form-group login-group-checkbox">
            <%= f.radio_button :gender,"male", id: 'male'%>
            <label for="male">male</label>

            <%= f.radio_button :gender, "female", id: 'female'%>
            <label for="female">female</label>
          </div>
        </div>
        <button type="submit" class="login-button"><i class="fa fa-chevron-right"></i></button>
      </div>
      <div class="etc-login-form">
        <p>already have an account? <%= link_to("login here", new_sessions_path) %></p>
      </div>
    <% end %>
  </div>
  <!-- end:Main Form -->
</div>

app/views/users/new.html.erb
<%= render 'users/register' %>