config/routes.rb
Rails.application.routes.draw do
  get 'index' => 'home#index'
  root 'home#index'
  resource :users
  resource :sessions, only: [:new, :create, :destroy]
  delete 'log_out' => 'sessions#destroy'

  resources :conversations do
    resources :messages
  end
  get 'conversations/display' => 'conversations#display'
  get 'conversations/load_more' => 'conversations#load_more'

  resources :friendships, only: [:create]
  get 'users/block' => 'users#block'
  get 'users/un_block' => 'users#un_block'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login

  def index
    @conversations = Conversation.order_by_messages
    @conversation = @conversations.first
  end

  def add_friends
    @friends = current_user.friends
  end

  def users_list
    @users = User.all
  end

  def block_list
    @blockers = current_user.blockers
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_compose.html.erb
<div class="p-15">
    <div class="dropdown">
        <a class="btn btn-primary btn-block" href="" data-toggle="dropdown">Messages <i class="caret m-l-5"></i></a>

        <ul class="dropdown-menu dm-icon w-100">
            <li><a href=""><i class="fa fa-envelope"></i> Messages</a></li>
            <li><a href=""><i class="fa fa-users"></i> Contacts</a></li>
            <li><a href=""><i class="fa fa-format-list-bulleted"> </i>Todo Lists</a></li>
        </ul>
    </div>
</div>

app/views/home/_current_user.html.erb
<div class="ms-user clearfix">
  <img src="<%= current_user.avatar_url || 'https://bootdey.com/img/Content/avatar/avatar1.png'%>" alt="" class="img-avatar pull-left">
  <div>Signed in as <br><%= current_user.email %> <%= link_to 'sign out', log_out_path, method: 'delete' %></div>
</div>

app/views/home/_friends.html.erb
<div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 550px;">
  <div class="chat-list-wrapper" style="overflow-y: auto; width: auto; height: 550px;">
    <% friends.each do |friend| %>
        <%= link_to conversations_display_path(user_id: current_user.id, recipient_id: friend.id), remote: true, class: 'list-group-item media' do %>
            <div class="pull-left">
                <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="" class="img-avatar">
            </div>
            <div class="media-body">
                <div class="list-group-item-heading"><%= friend.email %></div>
                <small class="list-group-item-text c-gray"><%= Conversation.last_conversation_message(current_user.id, friend.id) %></small>
            </div>
        <% end %>
    <% end %>
  </div>
  <div class="slimScrollBar" style="width: 7px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px; height: 478.639px; background: rgb(0, 0, 0);">
  </div>
  <div class="slimScrollRail" style="width: 7px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; opacity: 0.2; z-index: 90; right: 1px; background: rgb(51, 51, 51);">
  </div>
</div>

app/views/home/_index.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container bootstrap snippet">
    <div class="tile tile-alt" id="messages-main">
        <div class="ms-menu">
            <div class="ms-user clearfix">
                <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="" class="img-avatar pull-left">
                <div>Signed in as <br> m-hollaway@gmail.com</div>
            </div>
            
            <div class="p-15">
                <div class="dropdown">
                    <a class="btn btn-primary btn-block" href="" data-toggle="dropdown">Messages <i class="caret m-l-5"></i></a>
    
                    <ul class="dropdown-menu dm-icon w-100">
                        <li><a href=""><i class="fa fa-envelope"></i> Messages</a></li>
                        <li><a href=""><i class="fa fa-users"></i> Contacts</a></li>
                        <li><a href=""><i class="fa fa-format-list-bulleted"> </i>Todo Lists</a></li>
                    </ul>
                </div>
            </div>
            
            <div class="list-group lg-alt">
                <a class="list-group-item media" href="">
                    <div class="pull-left">
                        <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="" class="img-avatar">
                    </div>
                    <div class="media-body">
                        <small class="list-group-item-heading">Davil Parnell</small>
                        <small class="list-group-item-text c-gray">Fierent fastidii recteque ad pro</small>
                    </div>
                </a>
                
                <a class="list-group-item media" href="">
                    <div class="pull-left">
                        <img src="https://bootdey.com/img/Content/avatar/avatar3.png" alt="" class="img-avatar">
                    </div>
                    <div class="media-body">
                        <div class="list-group-item-heading">Ann Watkinson</div>
                        <small class="list-group-item-text c-gray">Cum sociis natoque penatibus </small>
                    </div>
                </a>
                
                <a class="list-group-item media" href="">
                    <div class="pull-left">
                        <img src="https://bootdey.com/img/Content/avatar/avatar4.png" alt="" class="img-avatar">
                    </div>
                    <div class="media-body">
                        <div class="list-group-item-heading">Marse Walter</div>
                        <small class="list-group-item-text c-gray">Suspendisse sapien ligula</small>
                    </div>
                </a>
                
                <a class="list-group-item media" href="">
                    <div class="lv-avatar pull-left">
                        <img src="https://bootdey.com/img/Content/avatar/avatar5.png" alt="" class="img-avatar">
                    </div>
                    <div class="media-body">
                        <div class="list-group-item-heading">Jeremy Robbins</div>
                        <small class="list-group-item-text c-gray">Phasellus porttitor tellus nec</small>
                    </div>
                </a>
                
                <a class="list-group-item media" href="">
                    <div class="lv-avatar pull-left">
                        <img src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="" class="img-avatar">
                    </div>
                    <div class="media-body">
                        <div class="list-group-item-heading">Reginald Horace</div>
                        <small class="list-group-item-text c-gray">Quisque consequat arcu eget</small>
                    </div>
                </a>
                
                <a class="list-group-item media" href="">
                    <div class="pull-left">
                        <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="" class="img-avatar">
                    </div>
                    <div class="media-body">
                        <div class="list-group-item-heading">Shark Henry</div>
                        <small class="list-group-item-text c-gray">Nam lobortis odio et leo maximu</small>
                    </div>
                </a>
                
                <a class="list-group-item media" href="">
                    <div class="pull-left">
                        <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="" class="img-avatar">
                    </div>
                    <div class="media-body">
                        <div class="list-group-item-heading">Paul Van Dack</div>
                        <small class="list-group-item-text c-gray">Nam posuere purus sed velit auctor sodales</small>
                    </div>
                </a>
                
                <a class="list-group-item media" href="">
                    <div class="lv-avatar pull-left">
                        <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="" class="img-avatar">
                    </div>
                    <div class="media-body">
                        <div class="list-group-item-heading">James Anderson</div>
                        <small class="list-group-item-text c-gray">Vivamus imperdiet sagittis quam</small>
                    </div>
                </a>
                
                <a class="list-group-item media" href="">
                    <div class="lv-avatar pull-left">
                        <img src="https://bootdey.com/img/Content/avatar/avatar3.png" alt="" class="img-avatar">
                    </div>
                    <div class="media-body">
                        <div class="list-group-item-heading">Kane Williams</div>
                        <small class="list-group-item-text c-gray">Suspendisse justo nulla luctus nec</small>
                    </div>
                </a>
            </div>
    
            
        </div>
        
        <div class="ms-body">
            <div class="action-header clearfix">
                <div class="visible-xs" id="ms-menu-trigger">
                    <i class="fa fa-bars"></i>
                </div>
                
                <div class="pull-left hidden-xs">
                    <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="" class="img-avatar m-r-10">
                    <div class="lv-avatar pull-left">
                        
                    </div>
                    <span>David Parbell</span>
                </div>
                 
                <ul class="ah-actions actions">
                    <li>
                        <a href="">
                            <i class="fa fa-trash"></i>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa fa-check"></i>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="fa fa-clock-o"></i>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="" data-toggle="dropdown" aria-expanded="true">
                            <i class="fa fa-sort"></i>
                        </a>
            
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li>
                                <a href="">Latest</a>
                            </li>
                            <li>
                                <a href="">Oldest</a>
                            </li>
                        </ul>
                    </li>                             
                    <li class="dropdown">
                        <a href="" data-toggle="dropdown" aria-expanded="true">
                            <i class="fa fa-bars"></i>
                        </a>
            
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li>
                                <a href="">Refresh</a>
                            </li>
                            <li>
                                <a href="">Message Settings</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
    
            <div class="message-feed media">
                <div class="pull-left">
                    <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="" class="img-avatar">
                </div>
                <div class="media-body">
                    <div class="mf-content">
                        Quisque consequat arcu eget odio cursus, ut tempor arcu vestibulum. Etiam ex arcu, porta a urna non, lacinia pellentesque orci. Proin semper sagittis erat, eget condimentum sapien viverra et. Mauris volutpat magna nibh, et condimentum est rutrum a. Nunc sed turpis mi. In eu massa a sem pulvinar lobortis.
                    </div>
                    <small class="mf-date"><i class="fa fa-clock-o"></i> 20/02/2015 at 09:00</small>
                </div>
            </div>
            
            <div class="message-feed right">
                <div class="pull-right">
                    <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="" class="img-avatar">
                </div>
                <div class="media-body">
                    <div class="mf-content">
                        Mauris volutpat magna nibh, et condimentum est rutrum a. Nunc sed turpis mi. In eu massa a sem pulvinar lobortis.
                    </div>
                    <small class="mf-date"><i class="fa fa-clock-o"></i> 20/02/2015 at 09:30</small>
                </div>
            </div>
            
            <div class="message-feed media">
                <div class="pull-left">
                    <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="" class="img-avatar">
                </div>
                <div class="media-body">
                    <div class="mf-content">
                        Etiam ex arcumentum
                    </div>
                    <small class="mf-date"><i class="fa fa-clock-o"></i> 20/02/2015 at 09:33</small>
                </div>
            </div>
            
            <div class="message-feed right">
                <div class="pull-right">
                    <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="" class="img-avatar">
                </div>
                <div class="media-body">
                    <div class="mf-content">
                        Etiam nec facilisis lacus. Nulla imperdiet augue ullamcorper dui ullamcorper, eu laoreet sem consectetur. Aenean et ligula risus. Praesent sed posuere sem. Cum sociis natoque penatibus et magnis dis parturient montes,
                    </div>
                    <small class="mf-date"><i class="fa fa-clock-o"></i> 20/02/2015 at 10:10</small>
                </div>
            </div>
            
            <div class="message-feed media">
                <div class="pull-left">
                    <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="" class="img-avatar">
                </div>
                <div class="media-body">
                    <div class="mf-content">
                        Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam ac tortor ut elit sodales varius. Mauris id ipsum id mauris malesuada tincidunt. Vestibulum elit massa, pulvinar at sapien sed, luctus vestibulum eros. Etiam finibus tristique ante, vitae rhoncus sapien volutpat eget
                    </div>
                    <small class="mf-date"><i class="fa fa-clock-o"></i> 20/02/2015 at 10:24</small>
                </div>
            </div>
            
            <div class="msb-reply">
                <textarea placeholder="What's on your mind..."></textarea>
                <button><i class="fa fa-paper-plane-o"></i></button>
            </div>
        </div>
    </div>
</div>

app/views/home/_topbar.html.erb
<div class="action-header clearfix">
    <div class="visible-xs" id="ms-menu-trigger">
        <i class="fa fa-bars"></i>
    </div>
    <div class="pull-left hidden-xs">
        <img src="<%= friend.avatar_url || 'https://bootdey.com/img/Content/avatar/avatar2.png' %>" alt="" class="img-avatar m-r-10">
        <div class="lv-avatar pull-left">
        </div>
        <span><%= friend.email %></span>
    </div>
    <ul class="ah-actions actions">
        <li>
            <%= link_to conversations_path(conversation_id: @conversation), method: :delete, data: { confirm: 'Are you sure?' } do %>
               <i class="fa fa-trash"></i>
            <% end %>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-check"></i>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-clock-o"></i>
            </a>
        </li>                             
        <li class="dropdown">
            <a href="" data-toggle="dropdown" aria-expanded="true">
                <i class="fa fa-bars"></i>
            <ul class="dropdown-menu dropdown-menu-right">
                <li>
                    <%= link_to 'sign out', log_out_path, method: 'delete' %></div>
                </li>
                <li>
                    <a href="#">Settings</a>
                </li>
            </ul>
        </li>
    </ul>
</div>

app/views/home/index.html.erb
<% if current_user.present? %>
  <div class="container-fluild bootstrap snippet">
      <div class="tile tile-alt" id="messages-main">
          <div class="ms-menu">
            <%= render 'home/current_user' %>
            <%= render 'home/compose' %>
            <div class="list-group lg-alt">
              <%= render 'home/friends', friends: @friends %>
            </div>
          </div>
          
          <div class="ms-body">
            <div id="topbar">
              <%= render 'home/topbar', friend: @friend, conversation: @conversation %>
            </div>
            <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 430px;">
              <div class="message-list-wrapper" style="overflow-y: auto; width: auto; height: 420px;" tabindex="500">
                <div id="messages-body">
                  <%= render 'conversations/messages', conversation: @conversation, page: @page %>
                </div>
              </div>
              <div class="slimScrollBar" style="width: 7px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px; height: 478.639px; background: rgb(0, 0, 0);">
              </div>
              <div class="slimScrollRail" style="width: 7px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; opacity: 0.2; z-index: 90; right: 1px; background: rgb(51, 51, 51);">
              </div>
            </div>
            <div id="messages-form">
              <%= render 'messages/form', conversation: @conversation %>
            </div>
          </div>
      </div>
  </div>
<% end %>
<%= subscribe_to "/messages/new" %>